export const COOKINGCLASSES_LOADING = 'COOKINGCLASSES_LOADING';
export const ADD_COOKINGCLASSES = 'ADD_COOKINGCLASSES';
export const COOKINGCLASSES_FAILED = 'COOKINGCLASSES_FAILED';

export const RECIPES_LOADING = 'RECIPES_LOADING';
export const ADD_RECIPES = 'ADD_RECIPES';
export const RECIPES_FAILED = 'RECIPES_FAILED';